// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDghxWm-YXCWvHhHZ4Hx54Sfa66hkd2irQ',
    appId: '1:617211849009:web:b65b1c118121b370146810',
    messagingSenderId: '617211849009',
    projectId: 'bakbokja-927af',
    authDomain: 'bakbokja-927af.firebaseapp.com',
    storageBucket: 'bakbokja-927af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFwhq-eIlSE6o_DG3isIb2udMk71S9J1A',
    appId: '1:617211849009:android:0d7cf60893c70c7b146810',
    messagingSenderId: '617211849009',
    projectId: 'bakbokja-927af',
    storageBucket: 'bakbokja-927af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhYD_JPqMOASk2MHSl_uYxSFmv6KHTyo',
    appId: '1:617211849009:ios:6a6eb3ccd1836489146810',
    messagingSenderId: '617211849009',
    projectId: 'bakbokja-927af',
    storageBucket: 'bakbokja-927af.appspot.com',
    iosClientId: '617211849009-0afi9mbmq3998boumtebp3hh6the22ms.apps.googleusercontent.com',
    iosBundleId: 'com.bokja.diary',
  );
}
